jobs:
    - job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
            
          - name: Execute Bash script
            run: bash ./IDP_terraform/bash_scripts/usageStatistic.sh
  
          